---
homebrew_taps:
  - homebrew/versions
  - homebrew/binary

homebrew_packages:
  - { name: git }
  - { name: tmux }
  - { name: tree }
  - { name: pkgconfig }
  - { name: python }
  - { name: pstree }
  - { name: ack }
  - { name: gpg }
  - { name: jq }
  - { name: coreutils }
  - { name: nmap }
  - { name: heroku-toolbelt }
  - { name: wget,
      install_options: enable-iri }
  - { name: openssl }
  - { name: llvm }